# Generated by Django 4.0 on 2023-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Music', 'Music'), ('Book', 'Book'), ('Others', 'Others')], max_length=255, null=True),
        ),
    ]
