# Generated by Django 4.0 on 2023-01-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_room_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
