# Generated by Django 4.0 on 2023-01-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_bookviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookViews',
        ),
    ]
