# Generated by Django 4.0 on 2023-01-18 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0049_delete_bookviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_replies',
            field=models.ManyToManyField(blank=True, related_name='review_replies', to='app.Review'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
