# Generated by Django 4.0 on 2023-01-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_review_review_replies_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='review_replies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.review'),
        ),
    ]
