# Generated by Django 4.0 on 2023-01-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_reply_review_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_replies',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
